channels:
  - defaults
  - conda-forge
dependencies:
  # - mkl-service>=2.3.0
  # - numpy>=1.19.2
  # - openblas=0.3.6
  # - pip>=20.3.3
  # - python=3.8
  # - scipy>=1.5.2
  # - setuptools>=51.3.3
  # - sympy>=1.7.1
  # - tectonic>=0.1.12
  # - pip
  - bzip2=1.0.8
  - ca-certificates=2024.6.2
  - libffi=3.4.2
  - libsqlite=3.45.3
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.3.1
  - pip=24.0
  - python=3.9.19
  - readline=8.2
  - setuptools=70.0.0
  - tk=8.6.13
  - wheel=0.43.0
  - xz=5.2.6
  # - pip:
  #     - matplotlib
  #     - exoplanet
  #     - starry
  #     - starry_process
  #     - lightkurve
  #     - arviz
  #     - corner
  #     - seaborn
  #     - pandas
  - pip:
      - aesara-theano-fallback==0.1.0
      - anyio==4.4.0
      - appnope==0.1.4
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - arviz==0.12.1
      - astropy==6.0.1
      - astropy-iers-data==0.2024.6.3.0.31.14
      - asttokens==2.4.1
      - async-lru==2.0.4
      - attrs==23.2.0
      - babel==2.15.0
      - beautifulsoup4==4.12.3
      - bleach==6.1.0
      - bokeh==3.4.1
      - cachetools==5.3.3
      - certifi==2024.6.2
      - cffi==1.16.0
      - cftime==1.6.4
      - charset-normalizer==3.3.2
      - cloudpickle==3.0.0
      - comm==0.2.2
      - cons==0.4.6
      - contourpy==1.2.1
      - corner==2.2.2
      - cycler==0.12.1
      - debugpy==1.8.1
      - decorator==5.1.1
      - defusedxml==0.7.1
      - deprecat==2.1.1
      - dill==0.3.8
      - etuples==0.3.9
      - exceptiongroup==1.2.1
      - executing==2.0.1
      - exoplanet==0.6.0
      - exoplanet-core==0.3.0
      - fastjsonschema==2.19.1
      - fastprogress==1.0.3
      - filelock==3.14.0
      - fonttools==4.53.0
      - fqdn==1.5.1
      - h11==0.14.0
      - h5netcdf==1.3.0
      - h5py==3.11.0
      - httpcore==1.0.5
      - httpx==0.27.0
      - idna==3.7
      - importlib-metadata==7.1.0
      - importlib-resources==6.4.0
      - ipykernel==6.29.4
      - ipympl==0.9.4
      - ipython==8.18.1
      - ipython-genutils==0.2.0
      - ipywidgets==8.1.3
      - isoduration==20.11.0
      - jedi==0.19.1
      - jinja2==3.1.4
      - json5==0.9.25
      - jsonpointer==2.4
      - jsonschema==4.22.0
      - jsonschema-specifications==2023.12.1
      - jupyter-client==8.6.2
      - jupyter-core==5.7.2
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.14.1
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.2.1
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.2
      - jupyterlab-widgets==3.0.11
      - kiwisolver==1.4.5
      - logical-unification==0.4.6
      - markupsafe==2.1.5
      - matplotlib==3.8.4
      - matplotlib-inline==0.1.7
      - minikanren==1.0.3
      - mistune==3.0.2
      - multipledispatch==1.0.0
      - nbclient==0.10.0
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - netcdf4==1.6.5
      - notebook-shim==0.2.4
      - numpy==1.22.1
      - overrides==7.7.0
      - packaging==24.0
      - pandas==2.0.3
      - pandocfilters==1.5.1
      - parso==0.8.4
      - patsy==0.5.6
      - pexpect==4.9.0
      - pillow==10.3.0
      - platformdirs==4.2.2
      - prometheus-client==0.20.0
      - prompt-toolkit==3.0.46
      - psutil==5.9.8
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pycparser==2.22
      - pyerfa==2.0.1.4
      - pygments==2.18.0
      - pymc3==3.11.6
      - pymc3-ext==0.1.1
      - pyparsing==3.1.2
      - pytensor==2.19.0
      - python-dateutil==2.9.0.post0
      - python-json-logger==2.0.7
      - pytz==2024.1
      - pyyaml==6.0.1
      - pyzmq==26.0.3
      - referencing==0.35.1
      - requests==2.32.3
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.18.1
      - scipy==1.7.3
      - semver==3.0.2
      - send2trash==1.8.3
      - setuptools-scm==8.1.0
      - six==1.16.0
      - sniffio==1.3.1
      - soupsieve==2.5
      - stack-data==0.6.3
      - terminado==0.18.1
      - theano-pymc==1.1.2
      - tinycss2==1.3.0
      - tomli==2.0.1
      - toolz==0.12.1
      - tornado==6.4.1
      - tqdm==4.66.4
      - traitlets==5.14.3
      - types-python-dateutil==2.9.0.20240316
      - typing-extensions==4.12.2
      - tzdata==2024.1
      - uri-template==1.3.0
      - urllib3==2.2.1
      - wcwidth==0.2.13
      - webcolors==24.6.0
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - widgetsnbextension==4.0.11
      - wrapt==1.16.0
      - xarray==2023.12.0
      - xarray-einstats==0.6.0
      - xyzservices==2024.6.0
      - zipp==3.19.2
