channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - pip:
      - matplotlib
      - exoplanet
      - starry
      - starry_process
      - lightkurve
      - arviz
      - corner
