name: build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build the article PDF
    concurrency: showyourwork-${{ github.ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Set up Python and fix dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pulp==2.7.0  # Install a version with the correct method name
      
      - name: Build the article PDF
        id: build
        uses: showyourwork/showyourwork-action@v2
        env:
          SANDBOX_TOKEN: ${{ secrets.SANDBOX_TOKEN }}
          OVERLEAF_EMAIL: ${{ secrets.OVERLEAF_EMAIL }}
          OVERLEAF_PASSWORD: ${{ secrets.OVERLEAF_PASSWORD }}
